--- 

- hosts: all
  become: true 
  tasks:

  - name: copy file to server
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 
